### ISSUE TITLE
Reimplement calculator as state machine

### ISSUE THREAD

**Issue by SindreBeba** [SindreBeba/calculator#12]
### Describe the new feature
I don't like the way the calculator logic is structured right now. It's unnecessarily hard to read and to follow. The way I track the last action already sort of resembles a state machine, so I believe that would be a better fit for this project. I will use xState instead of implementing it from scratch.

### Tasks
In addition to all the basic functionality, it's important that these special cases work with the new state machine logic as well:

- [x] Click on an operator instead of `=` to execute, show the result and use the result as the first operand in a new operation.
- [x] Click on an operator after `=` to use the result as the first operand in a new operation.
- [x] Click on `=` after an operator to use to first operand as both the first and second operand.
- [x] Click `=` multiple times to repeat the same operation.
- [x] Click on the delete button after clicking on an operator to remove the operator and go back to edit the first operand.
- [x] Have a maximum number of digits that are allowed during operand input.
- [x] Handle very big and very small numbers in an intuitive way.
- [x] Show an error in the display when dividing by zero.
